export const VIOLATION_UNIQUE_KEY_ERROR = 'Violation of unique key (carrierRntrc + licensePlate). Please update the record.'
export const ANTT_CACHE_RECORD_NOT_CREATED = 'ANTT validation Cache not created.'
export const ANTT_CACHE_RECORD_DELETED = 'ANTT cache deleted successfully.'
export const ANTT_CACHE_RECORD_CREATED_OR_UPDATED = 'ANTT validation Cache has been created / updated successfully.'
export const ANTT_CACHE_RECORD_NOT_FOUND_PARAMETERS = 'ANTT Cache not found on database for parameters:'
export const ANTT_CACHE_RECORD_NOT_FOUND_ID = 'ANTT Cache not found on database for provided id #'
export const ANTT_CACHE_EMPTY = 'There is no ANTT Cache information on database.'